FROM alpine:3.10

ARG CONSUL_TEMPLATE_VERSION=0.20.0

RUN apk update && \
    apk add nginx && \
    apk add curl && \
    mkdir -p /run/nginx && \
    cd /etc/nginx/conf.d && \
    mv default.conf default.conf.bak 

ADD https://releases.hashicorp.com/consul-template/${CONSUL_TEMPLATE_VERSION}/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip /usr/bin/
RUN unzip /usr/bin/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip && \
        mv consul-template /usr/local/bin/consul-template && \
    	rm -rf /usr/bin/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip

RUN rm -rf /etc/nginx/sites-enabled/default

COPY load-balancer.conf.ctmpl /etc/nginx/conf.d/

COPY consul-template-config.hcl /etc/

COPY docker-entrypoint.sh /etc/

CMD ["/bin/sh", "/etc/docker-entrypoint.sh"]
