version: "3"

services:
  nginx-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nginx-web
    ports:
      - "80"

  nginx-lb:
    build:
      context: .
      dockerfile: ./Dockerfile-nginx-lb
    depends_on:
      consul:
        condition: service_healthy
    image: nginx-lb
    ports:
      - "80:80"

  consul:
    image: consul:latest
    command: "agent -server -bootstrap -client 0.0.0.0 -ui"
    container_name: consul
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "8500:8500"
      - "8600:8600"

  registrator:
    image: gliderlabs/registrator:latest
    command: "-retry-attempts=-1 -resync=5 -ttl=300 -ttl-refresh=150 -cleanup  consul://consul:8500"
    container_name: registrator
    restart: on-failure
    depends_on:
      consul:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
